services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:prod"

  prisma:
    build:
      context: .
      dockerfile: prisma.Dockerfile
    container_name: nest_prisma
    ports:
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma studio"


  postgres:
    image: postgres:15
    container_name: postgres_db
    healthcheck:
          test: ['CMD-SHELL', 'pg_isready -U postgres']
          interval: 5s
          timeout: 5s
          retries: 5
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
